### PR TITLE
Created Regsiter And login page

### PR DESCRIPTION
**Pull request by Aparnaa-k**
Done with the Register and Login page also questionaire page

### CODE REVIEW

**Comment by yash0212** [comment]
This PR does have any files to be reviewed

**Review by yash0212 — CHANGES_REQUESTED** [review]
This PR does have any files to be reviewed

**Comment by Aparnaa-k** [comment]
Im not able to follow u @Yash Lotan ***@***.***>  Can u be bit
specific

**Comment by Aparnaa-k** [comment]
> This PR does have any files to be reviewed

**Pull request closed without merging**
